"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { formatBs } from "../../lib/nepali-date";

const money=(value:number)=>`Rs. ${Number(value||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const statusLabel=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export default function ClientPortal(){const router=useRouter();const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [tab,setTab]=useState<"overview"|"ledger"|"orders"|"shop">("overview");const [cart,setCart]=useState<Record<string,number>>({});const [notes,setNotes]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
  async function load(fiscalYearId?:string){try{if(data)setBusy(true);const response=await fetch(`/api/client${fiscalYearId?`?fy=${encodeURIComponent(fiscalYearId)}`:""}`,{cache:"no-store"});const body=await response.json();if(response.status===401){router.replace("/client-login");return}if(!response.ok){setNotice(body.error||"Portal could not load");return}setData(body)}catch{setNotice("Portal could not load. Check your connection and try again.")}finally{setLoading(false);setBusy(false)}}useEffect(()=>{void load()},[]);
  const cartLines=useMemo(()=>data?.products?.filter((product:any)=>Number(cart[product.id])>0).map((product:any)=>({...product,quantity:Number(cart[product.id]),amount:Number(cart[product.id])*Number(product.sale_price)}))||[],[cart,data]);const cartTotal=cartLines.reduce((sum:number,line:any)=>sum+line.amount,0);
  async function post(payload:any){setBusy(true);const response=await fetch("/api/client",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();setBusy(false);if(!response.ok){setNotice(body.error||"Request failed");return false}setData(body);setNotice(payload.action==="confirm_delivery"?"Delivery confirmed. Thank you.":"Order placed successfully");return true}
  async function placeOrder(){if(!cartLines.length)return setNotice("Choose at least one product");const ok=await post({action:"place_order",lines:cartLines.map((line:any)=>({productId:line.id,quantity:line.quantity})),notes});if(ok){setCart({});setNotes("");setTab("orders")}}
  async function logout(){await fetch("/api/client/auth/logout",{method:"POST"});router.replace("/client-login");router.refresh()}
  if(loading)return <main className="client-portal-loading"><span></span><strong>Opening your customer account…</strong></main>;
  if(!data)return <main className="client-login-page"><section className="client-login-card"><div className="client-login-copy"><small>CUSTOMER PORTAL</small><h1>We could not open your account</h1><p>{notice||"Please try signing in again."}</p></div><a className="client-login-link" href="/client-login">Return to customer login</a></section></main>;
  return <main className="client-portal"><header className="client-header"><div><img src="/hamro-afno-logo.jpeg" alt="Hamro Afno Enterprises"/><span><strong>{data.company.name}</strong><small>Customer Portal</small></span></div><div><span className="client-name">{data.party.name}</span><button onClick={logout}>Sign out</button></div></header><nav className="client-nav">{(["overview","ledger","orders","shop"] as const).map(item=><button className={tab===item?"active":""} key={item} onClick={()=>setTab(item)}>{item==="shop"?"Place order":statusLabel(item)}</button>)}</nav><section className="client-content">
    {tab==="overview"&&<><div className="client-welcome"><span>FY {data.fiscalYear.label_bs}</span><h1>Namaste, {data.party.name}</h1><p>Review your current account and track every order from acceptance to delivery.</p></div><div className="client-summary"><article><small>CURRENT BALANCE</small><strong>{money(data.balance)}</strong><span>{data.balance>=0?"Payable to Hamro Afno":"Advance balance"}</span></article><article><small>OPEN ORDERS</small><strong>{data.orders.filter((order:any)=>!["delivered","rejected","cancelled"].includes(order.status)).length}</strong><span>In current workflow</span></article><article><small>AVAILABLE PRODUCTS</small><strong>{data.products.length}</strong><span>Ready to order online</span></article></div><div className="client-overview-grid"><article className="client-card"><div className="client-card-head"><h2>Recent ledger activity</h2><button onClick={()=>setTab("ledger")}>View all</button></div>{data.ledger.slice(-5).reverse().map((row:any)=><div className="client-ledger-row" key={row.id}><span><strong>{row.reference}</strong><small>{formatBs(row.date)} · {row.particulars}</small></span><span><strong>{row.debit?money(row.debit):money(row.credit)}</strong><small>{row.debit?"Debit":"Credit"}</small></span></div>)}</article><article className="client-card"><div className="client-card-head"><h2>Recent orders</h2><button onClick={()=>setTab("orders")}>Track orders</button></div>{data.orders.slice(0,5).map((order:any)=><div className="client-order-brief" key={order.id}><span><strong>Order #{order.order_no}</strong><small>{formatBs(order.placed_at)}</small></span><span className={`client-status ${order.status}`}>{statusLabel(order.status)}</span></div>)}{!data.orders.length&&<p className="client-empty">No orders placed yet.</p>}</article></div></>}
    {tab==="ledger"&&<article className="client-card client-ledger"><div className="client-card-head"><div><h1>Account ledger</h1><p>Opening {money(data.opening)}</p></div><div className="client-ledger-controls"><select aria-label="Ledger fiscal year" value={data.fiscalYear.id} disabled={busy} onChange={event=>void load(event.target.value)}>{data.fiscalYears.map((year:any)=><option key={year.id} value={year.id}>FY {year.label_bs}{year.status==="open"?" · Current":""}</option>)}</select><strong>{money(data.balance)} {data.balance>=0?"Dr":"Cr"}</strong></div></div><div className="client-table-wrap"><table><thead><tr><th>DATE (BS)</th><th>REFERENCE</th><th>PARTICULARS</th><th>DEBIT</th><th>CREDIT</th><th>BALANCE</th></tr></thead><tbody>{data.ledger.map((row:any)=><tr key={row.id}><td>{formatBs(row.date)}</td><td><strong>{row.reference}</strong></td><td>{row.particulars}</td><td>{row.debit?money(row.debit):"—"}</td><td>{row.credit?money(row.credit):"—"}</td><td><strong>{money(row.balance)}</strong></td></tr>)}</tbody></table></div></article>}
    {tab==="orders"&&<section className="client-orders"><div className="client-section-head"><div><h1>Your orders</h1><p>Live status and complete order history.</p></div><button onClick={()=>setTab("shop")}>＋ Place new order</button></div>{data.orders.map((order:any)=><article className={`client-card client-order ${order.status}`} key={order.id}><div className="client-order-head"><span><small>ORDER</small><strong>#{order.order_no}</strong><em>{formatBs(order.placed_at,true)}</em></span><span className={`client-status ${order.status}`}>{statusLabel(order.status)}</span><span><small>TOTAL</small><strong>{money(order.total)}</strong></span></div><div className="client-order-lines">{order.customer_order_lines.map((line:any)=><div key={line.id}><span><strong>{line.product_name}</strong><small>{line.quantity} {line.unit} × {money(line.unit_price)}</small></span><strong>{money(line.amount)}</strong></div>)}</div>{order.notes&&<p className="client-order-note">Note: {order.notes}</p>}<div className="client-order-progress">{["accepted","preparing","packing","sent","delivered"].map((step,index)=>{const current=["pending","accepted","preparing","packing","sent","delivered"].indexOf(order.status);return <span className={current>index?"done":""} key={step}><i>{current>index?"✓":index+1}</i><small>{statusLabel(step)}</small></span>})}</div>{order.status==="sent"&&<button className="confirm-delivery" disabled={busy} onClick={()=>post({action:"confirm_delivery",orderId:order.id})}>✓ I received this order</button>}{order.status==="out_of_stock"&&<div className="client-order-alert">Some requested items are currently out of stock. Our team will contact you.</div>}</article>)}{!data.orders.length&&<div className="client-empty-state"><h2>No order history</h2><p>Choose available products and send your first order request.</p><button onClick={()=>setTab("shop")}>Browse products</button></div>}</section>}
    {tab==="shop"&&<section className="client-shop"><div className="client-section-head"><div><h1>Place an order</h1><p>Choose products and quantities. Our team will review stock and accept your request.</p></div><strong>{cartLines.length} items · {money(cartTotal)}</strong></div><div className="client-product-grid">{data.products.map((product:any)=><article className={Number(product.stock_qty)<=0?"sold-out":""} key={product.id}><div><span>{product.sku||"PRODUCT"}</span><h2>{product.name}</h2><p>{money(product.sale_price)} / {product.unit}</p></div><em>{Number(product.stock_qty)>0?`${product.stock_qty} ${product.unit} available`:"Out of stock"}</em><label>Quantity<input type="number" min="0" step="0.001" disabled={Number(product.stock_qty)<=0} value={cart[product.id]||""} onChange={event=>setCart({...cart,[product.id]:Math.max(0,Number(event.target.value))})}/></label></article>)}</div>{cartLines.length>0&&<aside className="client-cart"><div><span><strong>Order summary</strong><small>{cartLines.map((line:any)=>`${line.name} × ${line.quantity}`).join(" · ")}</small></span><strong>{money(cartTotal)}</strong></div><textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Delivery instructions or order note (optional)"/><button disabled={busy} onClick={placeOrder}>{busy?"Sending order…":"Place order request"}</button></aside>}</section>}
  </section>{notice&&<button className="client-toast" onClick={()=>setNotice("")}>{notice}</button>}</main>}
