"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function ClientLoginPage(){
  const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function login(){setBusy(true);setError("");const response=await fetch("/api/client/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"Could not sign in");return}router.replace("/client");router.refresh()}
  return <main className="client-login-page"><section className="client-login-card"><div className="client-login-brand"><img src="/hamro-afno-logo.jpeg" alt="Hamro Afno Enterprises"/><span><strong>Hamro Afno Enterprises</strong><small>Customer account</small></span></div><div className="client-login-copy"><small>CUSTOMER PORTAL</small><h1>Your account, orders and ledger</h1><p>Use the secure customer login provided by Hamro Afno Enterprises.</p></div><label>Email address<input autoFocus type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} onKeyDown={event=>event.key==="Enter"&&login()} autoComplete="current-password"/></label><a className="client-forgot-link" href="/client-forgot-password">Forgot password?</a>{error&&<div className="login-error">{error}</div>}<button className="client-login-button" disabled={busy||!email||!password} onClick={login}>{busy?"Signing in…":"Open customer portal"}</button><footer>Private access for registered customers only</footer></section></main>
}
