-- Run only in the dedicated Kritech Control Supabase project.
-- Adds the platform control centre. Company accounting data stays in each
-- company's dedicated Supabase project and is never copied into these tables.

alter table public.platform_tenants
  add column if not exists status text not null default 'active',
  add column if not exists contact_name text,
  add column if not exists contact_email text,
  add column if not exists contact_phone text,
  add column if not exists address text,
  add column if not exists notes text,
  add column if not exists onboarding_stage text not null default 'ready';

alter table public.platform_tenants drop constraint if exists platform_tenants_status_check;
alter table public.platform_tenants add constraint platform_tenants_status_check
  check (status in ('pending','active','suspended','expired'));
alter table public.platform_tenants drop constraint if exists platform_tenants_onboarding_stage_check;
alter table public.platform_tenants add constraint platform_tenants_onboarding_stage_check
  check (onboarding_stage in ('new','database','admin','domain','ready'));

alter table public.platform_companies
  add column if not exists legal_name text,
  add column if not exists project_ref text,
  add column if not exists region text,
  add column if not exists database_status text not null default 'pending',
  add column if not exists portal_enabled boolean not null default false,
  add column if not exists notes text;

alter table public.platform_companies drop constraint if exists platform_companies_database_status_check;
alter table public.platform_companies add constraint platform_companies_database_status_check
  check (database_status in ('pending','connecting','ready','error'));

create table if not exists public.platform_admins (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  name text not null,
  email text not null unique,
  role text not null default 'operator' check (role in ('super_admin','operator','support','viewer')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_subscriptions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null unique references public.platform_tenants(id) on delete cascade,
  plan_name text not null default 'Starter',
  status text not null default 'trial' check (status in ('trial','active','past_due','cancelled','expired')),
  starts_on date,
  expires_on date,
  company_limit integer not null default 1 check (company_limit > 0),
  user_limit integer not null default 10 check (user_limit > 0),
  monthly_amount numeric(14,2) not null default 0 check (monthly_amount >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.platform_admins(id) on delete set null,
  admin_email text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists platform_tenants_status_idx on public.platform_tenants(status, created_at desc);
create index if not exists platform_companies_status_idx on public.platform_companies(status, database_status);
create index if not exists platform_audit_logs_created_idx on public.platform_audit_logs(created_at desc);
create index if not exists platform_audit_logs_entity_idx on public.platform_audit_logs(entity_type, entity_id, created_at desc);

alter table public.platform_admins enable row level security;
alter table public.platform_subscriptions enable row level security;
alter table public.platform_audit_logs enable row level security;
revoke all on public.platform_admins from anon, authenticated;
revoke all on public.platform_subscriptions from anon, authenticated;
revoke all on public.platform_audit_logs from anon, authenticated;
grant all on public.platform_admins to service_role;
grant all on public.platform_subscriptions to service_role;
grant all on public.platform_audit_logs to service_role;
grant usage, select on sequence public.platform_audit_logs_id_seq to service_role;

insert into public.platform_admins (name, email, role, active)
values ('Prajwol Gautam', 'prajwolgautam56@gmail.com', 'super_admin', true)
on conflict (email) do update set
  name = excluded.name,
  role = excluded.role,
  active = true,
  updated_at = now();

insert into public.platform_subscriptions
  (tenant_id, plan_name, status, company_limit, user_limit, monthly_amount, notes)
select id, 'Internal', 'active', 2, 25, 0, 'Kritech internal Hamro workspace'
from public.platform_tenants where slug = 'hamro'
on conflict (tenant_id) do nothing;

update public.platform_companies set
  project_ref = 'qwxbacfnmumibihffdoj',
  region = 'ap-northeast-2',
  database_status = 'ready',
  updated_at = now()
where tenant_id = '10000000-0000-4000-8000-000000000001'
  and slug = 'hamro-afno';
