"use client";
import { useEffect,useState } from "react";
import { formatBs } from "../lib/nepali-date";
const money=(n:number)=>`Rs. ${Number(n||0).toLocaleString("en-IN")}`;
export default function ChequeWorkspace({onNotice}:{onNotice:(x:string)=>void}){
 const [data,setData]=useState<any>({rows:[],counts:{}});const [filter,setFilter]=useState("pending");const [busy,setBusy]=useState("");
 async function load(){try{const r=await fetch("/api/cheques",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e){onNotice(e instanceof Error?e.message:"Cheque register could not load")}}
 useEffect(()=>{load()},[]);
 async function update(id:string,status:string){setBusy(id);try{const r=await fetch("/api/cheques",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chequeId:id,status})});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);onNotice(status==="cleared"?"Cheque marked as cleared":"Cheque status updated")}catch(e){onNotice(e instanceof Error?e.message:"Update failed")}finally{setBusy("")}}
 const rows=data.rows.filter((x:any)=>filter==="all"||x.cheque_status===filter||(filter==="due"&&(x.due_today||x.overdue)));
 return <section className="cheque-workspace"><div className="module-hero cheque-hero"><div><span>CHEQUE CONTROL</span><h2>Cheque register</h2><p>Track every received cheque from receipt to bank clearance.</p></div><div className="cheque-hero-count"><strong>{data.counts.pending||0}</strong><small>Pending clearance</small></div></div><div className="cheque-stats"><button className={filter==="due"?"active":""} onClick={()=>setFilter("due")}><span>Due / overdue</span><strong>{(data.counts.dueToday||0)+(data.counts.overdue||0)}</strong><small>{data.counts.dueToday||0} to exchange today</small></button><button className={filter==="pending"?"active":""} onClick={()=>setFilter("pending")}><span>All pending</span><strong>{data.counts.pending||0}</strong><small>Waiting for clearance</small></button><button className={filter==="cleared"?"active":""} onClick={()=>setFilter("cleared")}><span>Cleared</span><strong>{data.counts.cleared||0}</strong><small>Successfully exchanged</small></button><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}><span>All cheques</span><strong>{data.rows.length}</strong><small>Full cheque history</small></button></div><article className="card cheque-list"><div className="card-title"><div><h3>{filter==="due"?"Cheques requiring attention":filter==="pending"?"Pending cheques":filter==="cleared"?"Cleared cheques":"All cheque records"}</h3><p>आज: {formatBs(data.today)}</p></div></div>{rows.length?<div className="cheque-rows">{rows.map((x:any)=><div className={`cheque-row ${x.overdue?"overdue":""}`} key={x.id}><div className="cheque-date"><strong>{formatBs(x.cheque_exchange_date)}</strong><small>{x.due_today?"Exchange today":x.overdue?`${x.days_pending} days overdue`:"Exchange date"}</small></div><div className="cheque-party"><strong>{x.party}</strong><small>{x.phone||"No phone"} · Receipt {x.voucher_no}</small></div><div><span className="cheque-number">{x.cheque_no||"No cheque no."}</span><small>{x.cheque_bank||"Bank not specified"}</small></div><div className="cheque-amount"><strong>{money(x.total)}</strong><small>Received {formatBs(x.voucher_date)}</small></div><span className={`cheque-status ${x.cheque_status}`}>{x.cheque_status}</span><div className="cheque-actions">{x.cheque_status==="pending"&&<><button className="clear-cheque" disabled={busy===x.id} onClick={()=>update(x.id,"cleared")}>✓ Cleared / Done</button><button disabled={busy===x.id} onClick={()=>update(x.id,"cancelled")}>Cancel</button></>}{x.cheque_status!=="pending"&&<button onClick={()=>update(x.id,"pending")}>Move to pending</button>}</div></div>)}</div>:<div className="empty-cheques"><i>✓</i><h3>No cheques in this view</h3><p>Cheque receipts will automatically appear here.</p></div>}</article></section>
}
