"use client";
import { useEffect, useMemo, useState } from "react";
import BsDateInput from "./bs-date-input";
import { formatBs } from "../lib/nepali-date";

const money=(value:number)=>`Rs. ${Number(value||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const accountLabel:Record<string,string>={bank:"Bank account",office_cash:"Office counter",employee_wallet:"Employee wallet"};
const movementLabel:Record<string,string>={customer_receipt:"Customer receipt",internal_transfer:"Cash transfer",outgoing_payment:"Payment given",expense:"Expense",office_deposit:"Office deposit",bank_deposit:"Bank deposit",opening_adjustment:"Opening balance"};

export default function FundsWorkspace({fiscalYear,onNotice}:{fiscalYear:any;onNotice:(message:string)=>void}){
  const [data,setData]=useState<any>({accounts:[],transferDestinations:[],movements:[],members:[],parties:[]});
  const [dialog,setDialog]=useState<"account"|"transfer"|"outgoing"|null>(null);
  const [selectedAccountId,setSelectedAccountId]=useState("");
  const [busy,setBusy]=useState(false);
  const [form,setForm]=useState<any>({accountType:"bank",date:today(),paymentMode:"Cash",asExpense:false});
  const load=async()=>{if(!fiscalYear?.id)return;const response=await fetch(`/api/funds?fy=${fiscalYear.id}`,{cache:"no-store"});const body=await response.json();if(!response.ok){onNotice(body.error||"Funds could not be loaded");return}setData(body)};
  useEffect(()=>{load()},[fiscalYear?.id]);
  const accounts=data.accounts||[];
  const transferDestinations=data.transferDestinations||accounts;
  const privileged=["admin","manager","accountant"].includes(data.currentMember?.role);
  const sourceAccounts=privileged?accounts:accounts.filter((account:any)=>account.account_type==="employee_wallet"&&account.team_member_id===data.currentMember?.id);
  const bankTotal=useMemo(()=>accounts.filter((x:any)=>x.account_type==="bank").reduce((sum:number,x:any)=>sum+Number(x.balance),0),[accounts]);
  const counterTotal=useMemo(()=>accounts.filter((x:any)=>x.account_type==="office_cash").reduce((sum:number,x:any)=>sum+Number(x.balance),0),[accounts]);
  const walletTotal=useMemo(()=>accounts.filter((x:any)=>x.account_type==="employee_wallet").reduce((sum:number,x:any)=>sum+Number(x.balance),0),[accounts]);
  const selectedAccount=accounts.find((account:any)=>account.id===selectedAccountId);
  const visibleMovements=(data.movements||[]).filter((movement:any)=>!selectedAccountId||movement.from_account_id===selectedAccountId||movement.to_account_id===selectedAccountId);
  function open(kind:"account"|"transfer"|"outgoing"){
    const sourceId=sourceAccounts[0]?.id||"";const destinationId=transferDestinations.find((account:any)=>account.id!==sourceId)?.id||"";
    setForm({accountType:"bank",date:today(),paymentMode:"Cash",asExpense:false,fromAccountId:sourceId,toAccountId:destinationId});setDialog(kind);
  }
  async function submit(){
    setBusy(true);const response=await fetch("/api/funds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,action:dialog==="account"?"add_account":dialog==="transfer"?"transfer":"outgoing_payment",fiscalYearId:fiscalYear.id})});const body=await response.json();setBusy(false);if(!response.ok){onNotice(body.error||"Could not save");return}setData(body);setDialog(null);onNotice(dialog==="account"?"Financial account added":dialog==="transfer"?"Cash transfer recorded":"Outgoing payment recorded");
  }
  return <section className="funds-workspace">
    <div className="module-hero funds-hero"><div><span>CASH CONTROL</span><h2>Cash & Bank</h2><p>Track company banks, office cash and every employee wallet from collection to deposit.</p></div><div className="hero-actions"><button className="primary soft" onClick={()=>open("account")}>＋ Add account</button><button className="primary soft" onClick={()=>open("transfer")}>⇄ Transfer / deposit</button><button className="primary" onClick={()=>open("outgoing")}>− Payment given</button></div></div>
    <div className="funds-summary"><article><small>COMPANY BANKS</small><strong>{money(bankTotal)}</strong><span>{accounts.filter((x:any)=>x.account_type==="bank").length} accounts</span></article><article><small>OFFICE COUNTER</small><strong>{money(counterTotal)}</strong><span>Physical office cash</span></article><article><small>WITH EMPLOYEES</small><strong>{money(walletTotal)}</strong><span>{accounts.filter((x:any)=>x.account_type==="employee_wallet"&&Number(x.balance)!==0).length} active balances</span></article><article><small>TOTAL CONTROLLED FUNDS</small><strong>{money(bankTotal+counterTotal+walletTotal)}</strong><span>Manual book balance</span></article></div>
    <div className="funds-grid">
      <article className="card funds-accounts"><div className="card-title"><div><h3>Accounts & wallets</h3><p>Choose one account to open its statement</p></div>{selectedAccountId&&<button onClick={()=>setSelectedAccountId("")}>All activity</button>}</div><div className="fund-account-list">{accounts.map((account:any)=><button key={account.id} onClick={()=>setSelectedAccountId(account.id)} className={`fund-account ${account.account_type} ${selectedAccountId===account.id?"selected":""}`}><span className="fund-account-icon">{account.account_type==="bank"?"▣":account.account_type==="office_cash"?"▤":"◎"}</span><span><strong>{account.name}</strong><small>{accountLabel[account.account_type]}{account.account_number?` · ${account.account_number}`:""}</small></span><span><strong className={Number(account.balance)<0?"negative":""}>{money(account.balance)}</strong><small>Opening {money(account.opening_balance)}</small></span></button>)}</div></article>
      <article className="card funds-activity"><div className="card-title"><div><h3>{selectedAccount?`${selectedAccount.name} statement`:"Money activity"}</h3><p>FY {fiscalYear?.label_bs} · {selectedAccount?"credit and debit activity":"newest first"}</p></div></div><div className="fund-movement-list">{visibleMovements.map((movement:any)=>{const moneyIn=selectedAccountId?movement.to_account_id===selectedAccountId:!movement.from_account_id;return <div key={movement.id}><span className={`movement-mark ${movement.status} ${moneyIn?"money-in":"money-out"}`}>{moneyIn?"＋":"−"}</span><span><strong>{movement.title}</strong><small>{movementLabel[movement.movement_type]||movement.movement_type} · {formatBs(movement.movement_date)}</small><em>{movement.from_account?.name||"External source"} → {movement.to_account?.name||movement.party?.name||"External payment"}</em></span><span><strong className={moneyIn?"money-in-text":"money-out-text"}>{moneyIn?"Credit":"Debit"} · {money(movement.amount)}</strong><small>{movement.generator?.name||"Office"}</small><i className={`movement-status ${movement.status}`}>{movement.status}</i></span></div>})}{!visibleMovements.length&&<div className="dashboard-empty">No cash or bank movement in this fiscal year.</div>}</div></article>
    </div>
    {dialog&&<div className="modal-backdrop" onMouseDown={()=>setDialog(null)}><section className="modal compact-modal funds-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><small>CASH CONTROL · FY {fiscalYear?.label_bs}</small><h2>{dialog==="account"?"Add financial account":dialog==="transfer"?"Transfer / deposit cash":"Record payment given"}</h2></div><button onClick={()=>setDialog(null)}>×</button></div><div className="form-grid">
      {dialog==="account"&&<><label>Account type<select value={form.accountType} onChange={event=>setForm({...form,accountType:event.target.value})}><option value="bank">Company bank account</option><option value="office_cash">Office cash counter</option></select></label><label>Display name<input autoFocus value={form.name||""} onChange={event=>setForm({...form,name:event.target.value})} placeholder="e.g. Nabil Bank Current"/></label>{form.accountType==="bank"&&<><label>Bank name<input value={form.bankName||""} onChange={event=>setForm({...form,bankName:event.target.value})}/></label><label>Account number<input value={form.accountNumber||""} onChange={event=>setForm({...form,accountNumber:event.target.value})}/></label></>}<label>Current / opening balance<input type="number" value={form.openingBalance||""} onChange={event=>setForm({...form,openingBalance:event.target.value})} placeholder="0.00"/></label></>}
      {dialog==="transfer"&&<><label>Cash currently held in<select value={form.fromAccountId||""} onChange={event=>{const sourceId=event.target.value;setForm({...form,fromAccountId:sourceId,toAccountId:form.toAccountId===sourceId?(transferDestinations.find((account:any)=>account.id!==sourceId)?.id||""):form.toAccountId})}}>{sourceAccounts.map((account:any)=><option key={account.id} value={account.id}>{account.name} · {money(account.balance)}</option>)}</select></label><label>Hand over / transfer to<select value={form.toAccountId||""} onChange={event=>setForm({...form,toAccountId:event.target.value})}>{transferDestinations.filter((account:any)=>account.id!==form.fromAccountId).map((account:any)=><option key={account.id} value={account.id}>{account.name} · {accountLabel[account.account_type]}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" value={form.amount||""} onChange={event=>setForm({...form,amount:event.target.value})}/></label><label>Date (BS)<BsDateInput min={fiscalYear.start_ad} max={fiscalYear.end_ad} value={form.date} onChange={value=>setForm({...form,date:value})}/></label><label className="full">Handover / transfer note<input value={form.title||""} onChange={event=>setForm({...form,title:event.target.value})} placeholder="Cash handed to staff / deposited at counter / bank"/></label><p className="fund-transfer-help full">Employee wallet → another employee, office counter or bank. Office counter → bank transfers are available to admin, manager and accountant.</p></>}
      {dialog==="outgoing"&&<><label>Paid from<select value={form.fromAccountId||""} onChange={event=>setForm({...form,fromAccountId:event.target.value})}>{accounts.map((account:any)=><option key={account.id} value={account.id}>{account.name} · {money(account.balance)}</option>)}</select></label><label>Payment mode<select value={form.paymentMode} onChange={event=>setForm({...form,paymentMode:event.target.value})}><option>Cash</option><option>Bank transfer</option><option>QR</option><option>Cheque</option></select></label><label>Paid to party (optional)<select value={form.partyId||""} onChange={event=>setForm({...form,partyId:event.target.value})}><option value="">General / other</option>{data.parties.map((party:any)=><option key={party.id} value={party.id}>{party.name}</option>)}</select></label><label>Amount<input type="number" value={form.amount||""} onChange={event=>setForm({...form,amount:event.target.value})}/></label><label>Date (BS)<BsDateInput min={fiscalYear.start_ad} max={fiscalYear.end_ad} value={form.date} onChange={value=>setForm({...form,date:value})}/></label><label>Posting<select value={String(form.asExpense)} onChange={event=>setForm({...form,asExpense:event.target.value==="true"})}><option value="false">Supplier / party payment</option><option value="true">Office expense</option></select></label><label className="full">Payment title / purpose<input autoFocus value={form.title||""} onChange={event=>setForm({...form,title:event.target.value})} placeholder="What was this payment for?"/></label></>}
    </div><div className="modal-actions"><button onClick={()=>setDialog(null)}>Cancel</button><button className="primary" disabled={busy} onClick={submit}>{busy?"Saving…":"Save record"}</button></div></section></div>}
  </section>
}
