"use client";

import { useEffect, useRef, useState } from "react";
import BsDateInput from "./bs-date-input";
import { formatBs } from "../lib/nepali-date";
import { downloadCsv, printDocument } from "../lib/export-data";

const money = (n: number) => `Rs. ${Math.abs(Number(n) || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const typeLabel: Record<string,string> = { sale: "Sales Invoice", receipt: "Payment Receipt", payment: "Payment Given", purchase: "Purchase", expense: "Office Expense", journal: "Journal" };
const reportLabel:Record<string,string>={daybook:"Day book",sales:"Sales register",purchases:"Purchase register",payments:"Payment receipt register",expenses:"Expense register",general_ledger:"General ledger",trial_balance:"Trial balance"};

export default function ReportsWorkspace({ parties, fiscalYear, initialPartyId, onNotice }: { parties: any[]; fiscalYear: any; initialPartyId: string; onNotice: (x:string)=>void }) {
  const now = new Date().toISOString().slice(0,10);
  const [partyId,setPartyId] = useState(initialPartyId || "");
  const [type,setType] = useState<"daybook"|"sales"|"purchases"|"payments"|"expenses"|"general_ledger"|"trial_balance">("daybook");
  const [accountId,setAccountId] = useState("");
  const [preset,setPreset] = useState<"today"|"fy"|"custom">(initialPartyId ? "fy" : "today");
  const [from,setFrom] = useState(initialPartyId ? fiscalYear?.start_ad || now : now);
  const [to,setTo] = useState(initialPartyId ? fiscalYear?.end_ad || now : now);
  const [data,setData] = useState<any>(null);
  const [loading,setLoading] = useState(false);
  const requestRef=useRef<AbortController|null>(null);

  useEffect(()=>{ if(initialPartyId){setPartyId(initialPartyId);setPreset("fy");setFrom(fiscalYear?.start_ad||now);setTo(fiscalYear?.end_ad||now)} },[initialPartyId,fiscalYear?.id]);
  useEffect(()=>{ if(!fiscalYear?.id)return; const timer=setTimeout(run,80); return()=>clearTimeout(timer) },[partyId,type,accountId,from,to,fiscalYear?.id]);
  function choosePreset(value: "today"|"fy"|"custom") { setPreset(value); if(value==="today"){setFrom(now);setTo(now)} if(value==="fy"){setFrom(fiscalYear.start_ad);setTo(fiscalYear.end_ad)} }
  async function run(){requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;setLoading(true);try{const q=new URLSearchParams({fiscalYearId:fiscalYear.id,type,from,to});if(partyId&&type!=="general_ledger"&&type!=="trial_balance")q.set("partyId",partyId);if(accountId&&type==="general_ledger")q.set("accountId",accountId);const key=`hae-report-${q}`;const cached=sessionStorage.getItem(key);if(cached)setData(JSON.parse(cached));const r=await fetch(`/api/reports?${q}`,{cache:"no-store",signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);sessionStorage.setItem(key,JSON.stringify(d))}catch(e){if((e as any)?.name!=="AbortError")onNotice(e instanceof Error?e.message:"Report could not load")}finally{if(requestRef.current===controller)setLoading(false)}}
  function exportReport(){if(!data?.rows?.length){onNotice("There is no report data to download");return}const name=`${type}-${data.party?.name||"all"}-${from}-to-${to}`;if(type==="trial_balance")downloadCsv(name,data.rows,[{label:"Code",value:(r:any)=>r.code},{label:"Account",value:(r:any)=>r.name},{label:"Opening Dr",value:(r:any)=>r.openingDebit},{label:"Opening Cr",value:(r:any)=>r.openingCredit},{label:"Period Dr",value:(r:any)=>r.debit},{label:"Period Cr",value:(r:any)=>r.credit},{label:"Closing Dr",value:(r:any)=>r.closingDebit},{label:"Closing Cr",value:(r:any)=>r.closingCredit}]);else if(type==="general_ledger")downloadCsv(name,data.rows,[{label:"Date (BS)",value:(r:any)=>formatBs(r.date)},{label:"Reference",value:(r:any)=>r.ref},{label:"Account",value:(r:any)=>`${r.accountCode} ${r.accountName}`},{label:"Particulars",value:(r:any)=>r.particulars},{label:"Debit",value:(r:any)=>r.debit},{label:"Credit",value:(r:any)=>r.credit},{label:"Balance",value:(r:any)=>r.balance??""}]);else downloadCsv(name,data.rows,[{label:"Date (BS)",value:(r:any)=>formatBs(r.date)},{label:"Reference",value:(r:any)=>r.ref},{label:"Type",value:(r:any)=>typeLabel[r.type]||r.type},{label:"Party",value:(r:any)=>r.party},{label:"Particulars",value:(r:any)=>r.particulars},{label:"Debit",value:(r:any)=>r.debit},{label:"Credit",value:(r:any)=>r.credit},{label:"Balance",value:(r:any)=>r.balance??""}]);}
  const balance = Number(data?.closing || 0);
  return <section className="reports-workspace">
    <div className="module-hero report-hero"><div><span>{partyId&&type!=="general_ledger"&&type!=="trial_balance" ? "PARTY LEDGER" : "ACCOUNTING REPORTS"}</span><h2>{data?.party?.name || reportLabel[type]}</h2><p>{partyId && data?.party ? [data.party.place,data.party.phone,data.party.tax_no ? `PAN: ${data.party.tax_no}` : ""].filter(Boolean).join(" · ") || "Complete debit, credit and running balance statement." : "Auditable double-entry reports for the selected fiscal period."}</p></div><div className="hero-actions"><button className="primary soft" onClick={exportReport}>⇩ Excel / CSV</button><button className="primary" onClick={()=>printDocument("report")}>Print / PDF</button></div></div>
    <article className="card report-filters">
      <label>Report<select value={type} onChange={e=>setType(e.target.value as any)}><option value="daybook">Full Day Book</option><option value="sales">Sales Register</option><option value="purchases">Purchase Register</option><option value="payments">Payment Receipt Register</option><option value="expenses">Expense Register</option><option value="general_ledger">General Ledger</option><option value="trial_balance">Trial Balance</option></select></label>
      {type!=="general_ledger"&&type!=="trial_balance"&&<label>Party / Client<select value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">All parties</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
      {type==="general_ledger"&&<label>Ledger account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">All accounts</option>{data?.accounts?.map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label>}
      <label>Period<select value={preset} onChange={e=>choosePreset(e.target.value as any)}><option value="today">Today</option><option value="fy">Full fiscal year</option><option value="custom">Custom dates</option></select></label>
      <label>From (BS)<BsDateInput min={fiscalYear.start_ad} max={fiscalYear.end_ad} value={from} onChange={value=>{setPreset("custom");setFrom(value)}}/></label>
      <label>To (BS)<BsDateInput min={fiscalYear.start_ad} max={fiscalYear.end_ad} value={to} onChange={value=>{setPreset("custom");setTo(value)}}/></label>
      <button onClick={run} disabled={loading}>{loading?"Loading…":"Apply report"}</button>
    </article>
    {partyId && data && type!=="general_ledger"&&type!=="trial_balance" && <div className="ledger-summary">
      <article><small>OPENING BALANCE</small><strong>{money(data.opening)}</strong><span>{data.opening>=0?"Debit":"Credit"}</span></article>
      <article><small>PERIOD DEBIT</small><strong>{money(data.totals.debit)}</strong><span>Sales / receivable</span></article>
      <article><small>PERIOD CREDIT</small><strong>{money(data.totals.credit)}</strong><span>Receipts / payable</span></article>
      <article className={balance>=0?"receive":"pay"}><small>CLOSING BALANCE</small><strong>{money(balance)}</strong><span>{balance>=0?"To receive from party":"To pay party"}</span></article>
    </div>}
    {!partyId && data && type!=="general_ledger"&&type!=="trial_balance" && <div className="ledger-summary"><article><small>TOTAL SALES</small><strong>{money(data.totals.sales)}</strong></article><article><small>PURCHASES</small><strong>{money(data.totals.purchases)}</strong></article><article><small>PAYMENTS RECEIVED</small><strong>{money(data.totals.receipts)}</strong></article><article><small>EXPENSES</small><strong>{money(data.totals.expenses)}</strong></article></div>}
    {type==="trial_balance"&&data&&<div className="ledger-summary"><article><small>PERIOD DEBIT</small><strong>{money(data.totals.debit)}</strong></article><article><small>PERIOD CREDIT</small><strong>{money(data.totals.credit)}</strong></article><article><small>CLOSING DEBIT</small><strong>{money(data.totals.closingDebit)}</strong></article><article className={data.balanced?"receive":"pay"}><small>CONTROL CHECK</small><strong>{data.balanced?"Balanced":"Out of balance"}</strong></article></div>}
    {type==="trial_balance"?<TrialBalanceTable data={data} loading={loading} from={from} to={to}/>:type==="general_ledger"?<GeneralLedgerTable data={data} loading={loading} from={from} to={to} accountId={accountId}/>:<VoucherReportTable data={data} loading={loading} from={from} to={to} partyId={partyId} type={type}/>}
  </section>
}

function TrialBalanceTable({data,loading,from,to}:{data:any;loading:boolean;from:string;to:string}) { return <article className="card report-table"><div className="card-title"><div><h3>Trial balance</h3><p>{formatBs(from)} देखि {formatBs(to)} · Debit and credit control</p></div></div><div className="table-wrap"><table><thead><tr><th>CODE</th><th>ACCOUNT</th><th>OPENING DR</th><th>OPENING CR</th><th>PERIOD DR</th><th>PERIOD CR</th><th>CLOSING DR</th><th>CLOSING CR</th></tr></thead><tbody>{data?.rows?.length?data.rows.map((r:any)=><tr key={r.id}><td><strong>{r.code}</strong></td><td>{r.name}<small className="table-subtitle">{r.accountType}</small></td><td>{r.openingDebit?money(r.openingDebit):"—"}</td><td>{r.openingCredit?money(r.openingCredit):"—"}</td><td className="debit">{r.debit?money(r.debit):"—"}</td><td className="credit">{r.credit?money(r.credit):"—"}</td><td>{r.closingDebit?money(r.closingDebit):"—"}</td><td>{r.closingCredit?money(r.closingCredit):"—"}</td></tr>):<tr><td className="empty-year" colSpan={8}>{loading?"Loading trial balance…":"No posted transactions for this period."}</td></tr>}</tbody>{data&&<tfoot><tr><td colSpan={2}><strong>Total</strong></td><td>{money(data.totals.openingDebit)}</td><td>{money(data.totals.openingCredit)}</td><td>{money(data.totals.debit)}</td><td>{money(data.totals.credit)}</td><td>{money(data.totals.closingDebit)}</td><td>{money(data.totals.closingCredit)}</td></tr></tfoot>}</table></div></article> }

function GeneralLedgerTable({data,loading,from,to,accountId}:{data:any;loading:boolean;from:string;to:string;accountId:string}) { return <article className="card report-table"><div className="card-title"><div><h3>General ledger</h3><p>{formatBs(from)} देखि {formatBs(to)} · {data?.rows?.length||0} journal lines</p></div></div><div className="table-wrap"><table><thead><tr><th>DATE (BS)</th><th>REFERENCE</th><th>ACCOUNT</th><th>PARTICULARS</th><th>DEBIT</th><th>CREDIT</th>{accountId&&<th>BALANCE</th>}</tr></thead><tbody>{data?.rows?.length?data.rows.map((r:any)=><tr key={r.id}><td>{formatBs(r.date)}</td><td><strong>{r.ref}</strong></td><td>{r.accountCode} · {r.accountName}</td><td>{r.particulars}</td><td className="debit">{r.debit?money(r.debit):"—"}</td><td className="credit">{r.credit?money(r.credit):"—"}</td>{accountId&&<td><strong>{money(r.balance)} {r.balance>=0?"Dr":"Cr"}</strong></td>}</tr>):<tr><td className="empty-year" colSpan={accountId?7:6}>{loading?"Loading general ledger…":"No journal lines for this filter."}</td></tr>}</tbody>{data&&<tfoot><tr><td colSpan={4}><strong>Period total</strong></td><td>{money(data.totals.debit)}</td><td>{money(data.totals.credit)}</td>{accountId&&<td>{money(data.closing)}</td>}</tr></tfoot>}</table></div></article> }

function VoucherReportTable({data,loading,from,to,partyId,type}:{data:any;loading:boolean;from:string;to:string;partyId:string;type:string}) { return <article className="card report-table"><div className="card-title"><div><h3>{partyId?"Ledger statement":type==="sales"?"Sales register":"Day book register"}</h3><p>{formatBs(from)} देखि {formatBs(to)} · {data?.rows?.length || 0} entries</p></div></div><div className="table-wrap"><table><thead><tr><th>DATE (BS)</th><th>REFERENCE</th><th>TYPE</th>{!partyId&&<th>PARTY / ACCOUNT</th>}<th>PARTICULARS</th><th>DEBIT</th><th>CREDIT</th>{partyId&&<th>BALANCE</th>}</tr></thead><tbody>{data?.rows?.length ? data.rows.map((r:any)=><tr key={r.id}><td>{formatBs(r.date)}</td><td><strong>{r.ref}</strong></td><td>{typeLabel[r.type]||r.type}</td>{!partyId&&<td>{r.party}</td>}<td>{r.particulars}{r.paymentMode?` · ${r.paymentMode}`:""}</td><td className="debit">{r.debit?money(r.debit):"—"}</td><td className="credit">{r.credit?money(r.credit):"—"}</td>{partyId&&<td><strong>{money(r.balance)} {r.balance>=0?"Dr":"Cr"}</strong></td>}</tr>):<tr><td className="empty-year" colSpan={partyId?8:7}>{loading?"Loading report…":"No transactions for this filter."}</td></tr>}</tbody>{data&&<tfoot><tr><td colSpan={5}><strong>Period total</strong></td><td className="debit"><strong>{money(data.totals.debit)}</strong></td><td className="credit"><strong>{money(data.totals.credit)}</strong></td>{partyId&&<td><strong>{money(data.closing)}</strong></td>}</tr></tfoot>}</table></div></article> }
